// <auto-generated />
using System;
using FolderBackuper.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FolderBackuper.Infrastructure.Database.Migrations
{
    [DbContext(typeof(FolderBackuperDbContext))]
    [Migration("20260817170226_InitialPersistence")]
    partial class InitialPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("FolderBackuper.Features.Backups.BackupArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationRootPath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("EffectivePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalizationState")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("OwnershipCreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("OwnershipExpectedLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnershipFileSystemIdentity")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnershipRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RetentionState")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StateChangedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId")
                        .IsUnique();

                    b.ToTable("BackupArtifacts", null, t =>
                        {
                            t.HasCheckConstraint("CK_BackupArtifacts_Size", "Size >= 0 AND OwnershipExpectedLength >= 0");
                        });
                });

            modelBuilder.Entity("FolderBackuper.Features.Backups.BackupRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("ArchiveBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CancellationRequestedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("CompressionDuration")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationRootPath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationSubfolder")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long>("DirectoryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("FinalCommitStartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FinalCommittedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NotificationErrorSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("NotificationState")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("QueuedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegionalCulture")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("RetentionCount")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("ScheduledTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScheduledWeekdays")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("SourceBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("TransferDuration")
                        .HasColumnType("TEXT");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "Outcome");

                    b.HasIndex("QueuedAtUtc", "Id");

                    b.ToTable("Runs", null, t =>
                        {
                            t.HasCheckConstraint("CK_Runs_CompletedOutcome", "(Outcome IS NULL AND CompletedAtUtc IS NULL) OR (Outcome IS NOT NULL AND CompletedAtUtc IS NOT NULL)");

                            t.HasCheckConstraint("CK_Runs_Counts", "FileCount >= 0 AND DirectoryCount >= 0 AND SourceBytes >= 0 AND ArchiveBytes >= 0");
                        });
                });

            modelBuilder.Entity("FolderBackuper.Features.Backups.RunProblem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DiagnosticDetail")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NativeErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserMessage")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("RunProblems", (string)null);
                });

            modelBuilder.Entity("FolderBackuper.Features.Backups.ScheduledOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ScheduleRevision")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("ScheduledLocalDate")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("ScheduledLocalTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("UtcOffsetMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RunId")
                        .IsUnique()
                        .HasFilter("RunId IS NOT NULL");

                    b.HasIndex("JobId", "ScheduleRevision", "ScheduledLocalDate")
                        .IsUnique();

                    b.ToTable("ScheduledOccurrences", (string)null);
                });

            modelBuilder.Entity("FolderBackuper.Features.Destinations.Destination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastAccessErrorSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastAccessResult")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastAccessSource")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastAccessedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<byte[]>("ProtectedPassword")
                        .HasColumnType("BLOB");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("SmbUsername")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("VerificationFingerprint")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("VerificationResult")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("VerifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Destinations", (string)null);
                });

            modelBuilder.Entity("FolderBackuper.Features.Jobs.BackupJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationOwnershipKey")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationSubfolder")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LatestArtifactBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long>("ManagedArtifactBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ManagedArtifactCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("RetentionCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ScheduleRevision")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("ScheduledTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StorageConfirmedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Weekdays")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("DestinationOwnershipKey")
                        .IsUnique()
                        .HasFilter("Lifecycle IN ('Active', 'Paused')");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Jobs", null, t =>
                        {
                            t.HasCheckConstraint("CK_Jobs_OwnershipKey", "Lifecycle = 'Archived' OR DestinationOwnershipKey IS NOT NULL");

                            t.HasCheckConstraint("CK_Jobs_RetentionCount", "RetentionCount >= 1");

                            t.HasCheckConstraint("CK_Jobs_StorageTotals", "ManagedArtifactCount >= 0 AND ManagedArtifactBytes >= 0 AND (LatestArtifactBytes IS NULL OR LatestArtifactBytes >= 0)");
                        });
                });

            modelBuilder.Entity("FolderBackuper.Features.Notifications.NotificationOutboxItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeliveredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FailedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSafeError")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PayloadVersion")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RunOutcome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("SendingAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId")
                        .IsUnique();

                    b.HasIndex("State", "CreatedAtUtc");

                    b.ToTable("NotificationOutbox", null, t =>
                        {
                            t.HasCheckConstraint("CK_NotificationOutbox_AttemptCount", "AttemptCount >= 0");

                            t.HasCheckConstraint("CK_NotificationOutbox_NotCancelled", "RunOutcome <> 'Cancelled'");
                        });
                });

            modelBuilder.Entity("FolderBackuper.Features.Settings.ApplicationSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NotificationProvider")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NotificationProviderConfiguration")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ProtectedNotificationSecret")
                        .HasColumnType("BLOB");

                    b.Property<string>("RecipientList")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstallationId")
                        .IsUnique();

                    b.ToTable("ApplicationSettings", (string)null);
                });

            modelBuilder.Entity("FolderBackuper.Features.Backups.BackupArtifact", b =>
                {
                    b.HasOne("FolderBackuper.Features.Backups.BackupRun", "Run")
                        .WithOne("Artifact")
                        .HasForeignKey("FolderBackuper.Features.Backups.BackupArtifact", "RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("FolderBackuper.Features.Backups.BackupRun", b =>
                {
                    b.HasOne("FolderBackuper.Features.Jobs.BackupJob", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("FolderBackuper.Features.Backups.RunProblem", b =>
                {
                    b.HasOne("FolderBackuper.Features.Backups.BackupRun", "Run")
                        .WithMany("Problems")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("FolderBackuper.Features.Backups.ScheduledOccurrence", b =>
                {
                    b.HasOne("FolderBackuper.Features.Jobs.BackupJob", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FolderBackuper.Features.Backups.BackupRun", "Run")
                        .WithOne("Occurrence")
                        .HasForeignKey("FolderBackuper.Features.Backups.ScheduledOccurrence", "RunId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Job");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("FolderBackuper.Features.Jobs.BackupJob", b =>
                {
                    b.HasOne("FolderBackuper.Features.Destinations.Destination", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("FolderBackuper.Features.Notifications.NotificationOutboxItem", b =>
                {
                    b.HasOne("FolderBackuper.Features.Backups.BackupRun", "Run")
                        .WithOne("Notification")
                        .HasForeignKey("FolderBackuper.Features.Notifications.NotificationOutboxItem", "RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("FolderBackuper.Features.Backups.BackupRun", b =>
                {
                    b.Navigation("Artifact");

                    b.Navigation("Notification");

                    b.Navigation("Occurrence");

                    b.Navigation("Problems");
                });
#pragma warning restore 612, 618
        }
    }
}
